# Generated by Django 5.2.12 on 2026-03-11 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('football', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='date_of_birth',
        ),
    ]
